Increase contrast of collection box in search results
pulibrary/pulfalight pull request #1110
Opened 2022-08-01 15:02 UTC by m-ichelleliu

Closes #1015

Before:
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/91390445/182179455-b3cfb884-30a0-4409-910a-a741894db1a1.png">
After:
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/91390445/182179511-db04a735-c1f1-4c81-bbd6-c340383e7ffa.png">

2022-08-01 15:05 UTC, hackartisan requested changes
@m-ichelleliu It looks really nice! Did you pull this color from somewhere else in the project? I'm wondering if it's close to anything in https://github.com/pulibrary/pulfalight/blob/main/app/assets/stylesheets/variables/colors.scss and if not maybe we could add it there and give it a name, then use it here by name.

2022-08-01 15:06 UTC, hackartisan commented
A potentially helpful line of reference if we try my suggestion: https://github.com/pulibrary/pulfalight/blob/ec2bb7a682e3fbfbd484f613202c51d6b000ab1a/app/assets/stylesheets/_overrides.scss#L2

2022-09-16 16:08 UTC, taylor-yamashita commented
I was able to pass the same Circle CI failing contrast test in #1108 by using `$bleu-de-france-darker: #23578b;` (slightly darker blue pulled from the lux palettes) for the links instead of the usual blue.

2022-09-19 21:32 UTC, m-ichelleliu commented
yay! Once your change is merged in I'll update mine to account for the new color

2022-09-26 12:43 UTC, hackartisan approved these changes
👍🏻 This looks good and it seems like it will make the collection entry stand out more.

2022-09-26 12:43 UTC, merged