Adds online access banner to collection page
pulibrary/pulfalight pull request #1261
Opened 2023-07-06 18:33 UTC by sdellis

2023-07-07 18:47 UTC, eliotjordan requested changes
This looks nice. I've got a few questions and an issue that should be fixed. In addition
1. could you close the related Github issue in the commit message? `Closes #...` 
2. A screen shot would be helpful as well.
3. Might be a good idea to fixup your git commits and give it a new commit message.

2023-07-07 18:47 UTC, eliotjordan commented on app/assets/stylesheets/modules/_document_access_badge.scss
> +  // // background-image: image-url("slant.png");
question: do we still need the slant.png file since it's not being used in the css? Also, Is the online-access-bg image being used?

2023-07-07 18:47 UTC, eliotjordan commented on app/assets/stylesheets/modules/_document_access_badge.scss
> +  // clip-path: polygon(0 0, 100% 0, calc(100% - 20px) 100%, 0 100%);
issue: we should we remove commented out code

2023-07-07 19:54 UTC, sdellis commented
@eliotjordan thanks for the review. I addressed your comments and I think we should be good now.

2023-07-07 20:07 UTC, eliotjordan requested changes
The `online-access-bg.png` file should be removed as well, right?

2023-07-10 20:06 UTC, sdellis commented
@eliotjordan Sorry, I missed removing that image. I also made a change to the green color in the banner to ensure the contrast meets WCAG 2.1 AA accessibility guideline criteria.

2023-07-10 23:54 UTC, tpendragon commented
This is real nice, just needs rebased.

2023-07-11 18:31 UTC, eliotjordan approved these changes

2023-07-11 18:32 UTC, merged