Implements a new view for an expanded finding aid collection
pulibrary/pulfalight pull request #435
Opened 2020-10-23 03:47 UTC by jrgriffiniii

Advances #89, but I would like to first please request some feedback before finalizing this.

2020-10-28 03:28 UTC, jrgriffiniii commented
There was a bug with this originally, and only a limited number of child documents were rendered. Also, the Table of Contents widget was not expanded:

![image](https://user-images.githubusercontent.com/1443986/97387254-073fdf00-18ac-11eb-9357-07e41c6d9c26.png)

2020-11-03 18:39 UTC, jrgriffiniii commented
This needs to be rebased.

2020-11-06 15:41 UTC, eliotjordan reviewed
@jrgriffiniii A few thoughts / questions:

1. We will need an expanded view button on the TOC header bar to be compliant with the wireframes.
1. The component titles should be links that take the user to the component. Right?
1. I wonder about expanding the TOC. The wireframe has it closed and it just seems like unnecessary and duplicative information to me.
1. From the wireframes, it looks like we need more metadata for components at a certain level. Looks like "Scope note" in the drawings. I'm not sure if that's correct or just filler.

2020-11-19 04:08 UTC, jrgriffiniii commented
https://github.com/pulibrary/pulfalight/pull/435/commits/59ff113557183ebde1fd87dda4717177b41a78d7 introduces the metadata for components with `scope note` and `arrangement`, as well as an `expand` and `collapse` button:
![image](https://user-images.githubusercontent.com/1443986/99620115-d5292500-29f2-11eb-9831-dfc7614f4eec.png)

![image](https://user-images.githubusercontent.com/1443986/99620077-bdea3780-29f2-11eb-9d04-fd409a1ba28c.png)

2020-11-19 04:59 UTC, jrgriffiniii commented
https://github.com/pulibrary/pulfalight/pull/435/commits/9f766d2b47b2841b75bd4157b001ade966ca4bda ensures that component titles are links and improves the styling for the extent badges:

![image](https://user-images.githubusercontent.com/1443986/99623428-18d35d00-29fa-11eb-8e6d-13fe24daea5d.png)

2020-11-19 05:02 UTC, jrgriffiniii commented
https://github.com/pulibrary/pulfalight/pull/435/commits/cbe210e9f31b57a09ca56e18c883eeb40534727f ensures that the Table of Contents component is collapsed for the expanded Collection View.

2020-11-20 07:01 UTC, jrgriffiniii commented
Rebasing this introduced a number of test failures which I'm now having difficulty reproducing locally. I suspect that this might be due to some updates applied to the EAD XML fixtures used during some the tests.

2020-11-23 16:48 UTC, eliotjordan requested changes
@jrgriffiniii  I have one code comment so far and a serious concern about performance. After experimenting a little, it seems that the SolrDocumentTree is making a single solr query for each child document. This works OK in dev with fixtures, but caused a serious problem on staging when trying to build the tree for the full Toni Morrison collection. The way I solved this for the TOC was to make one Solr request for the entire collection document with all of it's nested children and then parse that in the Ruby.

2020-11-23 17:25 UTC, eliotjordan commented on spec/models/solr_document_tree_spec.rb
> +      Rails.root.join("spec", "fixtures", "aspace", "generated", "publicpolicy", "MC152.EAD.xml")
No need to index this record again. It's already a fixture. On line 34, you could just use `SolrDocument.find("MC152")`

2020-11-23 21:35 UTC, jrgriffiniii commented
https://pulfalight-staging.princeton.edu/catalog/MC120?expanded=true is still quite slow even with https://github.com/pulibrary/pulfalight/pull/435/commits/0b2440f1772e7d1c14178d5c747e17ceb409fe9d, but there were definitely improvements. My suspicion is that this might also just be traversing of the nested Solr Documents.

2020-11-25 17:06 UTC, eliotjordan approved these changes

2020-11-25 18:00 UTC, merged