Redirect legacy pulfa URIs to new pulfalight path
pulibrary/pulfalight pull request #689
Opened 2021-02-24 19:31 UTC by bess

Connected to #639

2021-02-24 19:39 UTC, tpendragon requested changes
This is great! Can you add a test for collection IDs with periods in them?

See for example https://findingaids.princeton.edu/collections/MC001.02.01/c00003

Edit: Also, does this do a 301? Maybe a test for the code would be good too?

2021-02-24 20:29 UTC, bess commented
@tpendragon Take another look when you get a chance?

2021-02-24 21:47 UTC, tpendragon requested changes

2021-02-24 21:47 UTC, tpendragon commented on spec/requests/catalog_request_spec.rb
> +      expect(response).to redirect_to("http://www.example.com/catalog/MC001.02.01_c00003")
I'm real sorry to do this to you, and it's probably going to complicate things, but the actual URL is https://findingaids-beta.princeton.edu/catalog/MC001-02-01_c00003. I should have remembered, my bad.

2021-02-25 16:29 UTC, bess commented
@tpendragon Take another look?

2021-02-25 17:46 UTC, tpendragon approved these changes
This is great! Good work!

2021-02-25 17:47 UTC, merged