Updates the biographical collection note layout
pulibrary/pulfalight pull request #884
Opened 2021-08-31 16:57 UTC by jrgriffiniii

Resolves #718 by implementing an updated design for the collection show pages:

![image](https://user-images.githubusercontent.com/1443986/131544833-50f39bc8-ca7a-4c60-b937-cdb7019dce81.png)

2021-08-31 17:26 UTC, jrgriffiniii commented on spec/requests/catalog_request_spec.rb
> +    xit "renders the bioghist notes on the collection show page with <hr />" do
This should not be failing (I am not certain what is triggering this, but should the last CircleCI build pass, I will remove this).

2021-08-31 17:51 UTC, tpendragon requested changes
This looks good, but we'll have to wait until Lyrasis installs our updated plugin in aspace-staging and then refresh all the fixtures (delete spec/fixtures/aspace/generated and run `rake pulfalight:fixtures:refresh_aspace_fixtures` then fix any test failures.) I assume you manually copied in C0292, but we need to avoid not being able to refresh the fixtures as much as possible.

2021-09-01 20:00 UTC, tpendragon commented
@jrgriffiniii Can you update the rest of the EADs as well? Or at least those that haven't changed drastically (to the point irrelevant tests won't pass)

2021-09-02 15:21 UTC, jrgriffiniii commented
I am sorry for the delay with this, I am currently experiencing the following recurring error:

```bash
I, [2021-09-02T10:15:07.798679 #75113]  INFO -- : Regenerated AC259
rake aborted!
MultiXml::ParseError: 96:6604686: FATAL: Premature end of data in tag c line 96
[...]/pulfalight/app/services/aspace_fixture_generator.rb:179:in `get_content'
```

2021-09-02 15:22 UTC, tpendragon commented
What's after AC259? That looks like maybe an EAD with ruby errors in it is coming out?

2021-09-02 15:43 UTC, jrgriffiniii commented
I'm going to try and restart my environment, I'm receiving this:

```bash
$ curl -H "X-ArchivesSpace-Session: $SESSION" "https://aspace-staging.princeton.edu/staff/api/repositories/3/resource_descriptions/1769"
{"error":"Sinatra::NotFound"}
```

These IDs were parsed by debugging through the Ruby code base.

2021-09-02 16:26 UTC, jrgriffiniii commented
I apologize, I am still having this problem, it appears to just affect `MC016`:

```
170: def fixture_files
    171:   @fixture_files ||=
    172:     begin
    173:       #ead_ids.lazy.map do |eadid|
    174:       ['MC016'].lazy.map do |eadid|
    175:         binding.pry
[1] pry(#<AspaceFixtureGenerator>)> eadid
=> "MC016"
[2] pry(#<AspaceFixtureGenerator>)> uri, repo_code = client.ead_url_for_eadid(eadid: eadid)&.first
=> ["repositories/3/resource_descriptions/1769", "publicpolicy"]
[3] pry(#<AspaceFixtureGenerator>)> uri, repo_code = client.ead_url_for_eadid(eadid: eadid)
=> {"repositories/3/resource_descriptions/1769"=>"publicpolicy"}
```

The `client` here is configured for the staging environment:

```
=> #<Aspace::Client:0x00007f87f282cfb8
 @config=
  #<ArchivesSpace::Configuration:0x00007f87f29e80c8
   @base_repo="",
   @base_uri="https://aspace-staging.princeton.edu/staff/api",
```

...and this cannot be resolved from the staging server:

```
[STAGING_HOST]:~$ curl -H "X-ArchivesSpace-Session: $SESSION" "https://aspace-staging.princeton.edu/staff/api/repositories/3/resource_descriptions/1769"
{"error":"Sinatra::NotFound"}
```

2021-09-02 16:33 UTC, jrgriffiniii commented
While I have forcibly-published this within the staging environment, this does not seem to have assisted:

![image](https://user-images.githubusercontent.com/1443986/131882442-d236f0d3-867c-40b4-9b36-453e729a4456.png)

I will try and see about fixing the failing test before returning to this.

2021-09-03 14:04 UTC, jrgriffiniii commented
https://github.com/pulibrary/pulfalight/compare/issues-718-jrgriffiniii-biohist-wip?expand=1 just has the fixtures for C0292 replaced by using the GUI to download the affected ArchivesSpace Resources manually. This is passing on CircleCI: https://app.circleci.com/pipelines/github/pulibrary/pulfalight?branch=issues-718-jrgriffiniii-biohist-wip

2021-09-03 15:57 UTC, jrgriffiniii commented
Deprecated by https://github.com/pulibrary/pulfalight/pull/895

2021-09-03 15:57 UTC, closed without merging